disabled = false
languageCode = "zh-cn"
languageName = "Chinese"
weight = 1
title = "CyanScholar"

[params]
displayName = "CN"
isoCode = "zh-cn"
rtl = false
dateFormat = "2006 January 2"
logo = "icon.png"
hasCJKLanguage = true

[params.author]
name = "空青"
image = "cyan.jpg"
headline = "CyanScholar"
# links = "https://github.com/CyanStarNight"
bio = "工作是为了影响世界，兴趣是为了服务自己。"
