disabled = false
languageCode = "zh-cn"
languageName = "Chinese"
weight = 1
title = "CyanScholar"

[params]
displayName = "CN"
isoCode = "zh-cn"
rtl = false
dateFormat = "2006 January 2"
logo = "star.svg"

[params.author]
name = "空青"
image = "cyan.jpg"
headline = "CyanScholar"
# links = "https://github.com/CyanStarNight"
bio = "待补充"
